### ISSUE TITLE
News channel echo

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/cj#10]
From @Crayder: When a news item is posted, CJ can echo it to `@everyone` in the primary channel.

**Comment by WopsS** [comment]
I think this feature is not needed because we can see the channel marked as unread. Maybe a better feature will be to post a news and tag `@everyone` when someone post a new topic on the forums at [News and Updates](http://forum.sa-mp.com/forumdisplay.php?f=74), but we need to check the forum for new topics every X minutes.

**Comment by JohnyMac** [comment]
That forum gets a new thread every like a year lol... if its going to check for new topic, I think it should be done every day or something.. not every few minutes.

**Comment by WopsS** [comment]
I know, but if they post a new topic in that forum at 04:00 the bot will wait until next day at 00:00 or when the next check is to post it in Discord channel.

**Comment by Southclaws** [comment]
An hourly check is fine, we could minimise load by simply storing a MD5 hash of the archive page: http://forum.sa-mp.com/archive/index.php/f-74.html and comparing that every hour. If the hash doesn't match, then and only then run the scraper.

**Comment by Crayder** [comment]
>I think this feature is not needed because we can see the channel marked as unread

People would pay much more attention to mentions than they would a white dot next to the news channel...
