### ISSUE TITLE
Possibility for infinite loop with /impersonate

### ISSUE THREAD

**Issue by Vince0789** [Southclaws/cj#83]
If the output of /impersonate produces another /impersonate command, then it looks like that command will execute too (operators exempt from cooldown?). This may get progressively worse as more and more people use the command.

**Comment by Southclaws** [comment]
Yep, I'm not actually sure how to solve this one with the current state:

- If a command fails (returns a non-nil error) the cooldown is not set - otherwise it would get real annoying to wait for retries
- Commands are handled asynchronously
- /impersonate takes some time to complete and will not set a cooldown until finished

I don't want to set a cooldown before, incase the command fails - unless I unset the cooldown after but this feels hacky.

One solution I can think of is make (some?) commands atomic so only one of them can ever be running at once. Essentially build a queue mechanism with a concurrent producer, single consumer model.

**Comment by Southclaws** [comment]
Removed the command so closing.
